# Generated by Django 4.2 on 2024-08-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_remove_producto_camara'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
