# Generated by Django 4.2 on 2024-08-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pantalla',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='producto',
            name='procesador',
            field=models.CharField(max_length=500),
        ),
    ]
